### ISSUE TITLE
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.

### ISSUE THREAD

**Issue by syddharth** [dustysys/ddetailer#15] opened 2022-12-05 07:43 UTC
I did get the script to run once in a previous install, but after a clean reinstallation of webui for SD2.0, unable to get the script loaded.

**Comment by drandarov-io** [comment] 2022-12-12 12:24
Same

**Comment by illtellyoulater** [comment] 2023-01-31 00:38
I think this is a duplicate of https://github.com/dustysys/ddetailer/issues/20

**Comment by mudashi33** [comment] 2023-03-01 10:35
I encountered the same problem, it was still useless after reinstalling mmcv and mmdet. Finally, it was solved after reinstalling mmcv 1.7.0
`pip uninstall mmcv-full`
`mim install mmcv-full==1.7.0`

**Closed as completed** 2023-03-03 05:22 UTC
